version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/.github/workflows"
      - "/.github/actions/*"
    groups:
      ci:
        patterns: ["*"]
    schedule:
      interval: "cron"
      cronjob: "0 0 1 2,4,6,8,12 *"
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    directory: "/"
    groups:
      dependencies:
        patterns: ["*"]
    schedule:
      interval: "cron"
      cronjob: "0 0 1 2,4,6,8,12 *"
    cooldown:
      default-days: 7
