name: "Set up environment in CI"
description: "Installs Mise, with all tools and project dependencies, with caching"

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache-web
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: node_modules
        key: "dependencies-${{ hashFiles('.mise/config.toml', 'package-lock.json') }}"

    - name: Set up Mise
      uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
