name: "Set up environment in CI"
description: "Installs Mise, with all tools and project dependencies, with caching"

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache-web
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: node_modules
        key: "dependencies-${{ hashFiles('.mise/config.toml', 'package-lock.json') }}"

    - name: Set up Mise
      uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
