name: "Set up environment in CI"
description: "Installs Mise, with all tools and project dependencies, with caching"

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache-web
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: node_modules
        key: "dependencies-${{ hashFiles('.mise/config.toml', 'package-lock.json') }}"

    - name: Set up Mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
