[clean]
description = "Remove all untracked or safe to remove files"
run = "git clean -fdx -e .env -e .vercel"

[serve]
description = "Serve api with hot reloading on changes"
run = ["npm ci", "npx vercel dev"]
