["psn:auth"]
description = "Open Safari to manually authenticate with PSN"
run = "open -a Safari https://psn-api.achievements.app/authentication/authenticating-manually"

["psn:sync-auth-and-deploy"]
description = "Deploy API with updated playstation auth from local .env"
run = [
    "mise run env-upload:psn", 
    "mise run deploy"
]

["env-upload"]
description = "Upload all local .env variables to Vercel"
run = "python scripts/sync-env.py"

["env-upload:psn"]
description = "Upload local playstation auth from .env to Vercel"
run = "python scripts/sync-env.py PLAYSTATION_NPSSO"
