

[env-download]
description = "Download current .env production variables from Vercel"
run = "npx vercel pull --environment=production"

[deploy]
description = "Deploy current local api to Vercel (also done in ci on push to main)"
run = "npx vercel deploy --prod"
