on:
  workflow_call:
  workflow_dispatch:

jobs:
  linting-and-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Linting and Formatting
        run: npm run check

      - name: Compile
        run: npm run compile
