on:
  workflow_call:
  workflow_dispatch:

jobs:
  linting-and-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4

      - name: Install Dependencies
        run: npm ci

      - name: Biome Check
        run: npx biome check

      - name: Typescript Compile
        run: npx tsc --noEmit
